CREATE TABLE if not exists film_mpa_rating
(
    id          int not null PRIMARY KEY,
    name        varchar(10)
);

CREATE TABLE if not exists genre
(
    id   int PRIMARY KEY not null,
    name varchar(50)
);

CREATE TABLE if not exists films
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name          varchar(50)     NOT NULL,
    description   varchar(200),
    release_date  date            NOT NULL,
    duration      int,
    rating_mpa_id int references film_mpa_rating (id)
);

CREATE TABLE if not exists film_genre
(
    film_id      int references films (id),
    genre_id     int references genre (id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE if not exists users
(
    id           int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        varchar(50),
    login        varchar(50),
    name         varchar(50),
    birthday     date,
    UNIQUE (email),
    UNIQUE (login),
    PRIMARY KEY (id)
);

CREATE TABLE if not exists user_film_likes
(
    film_id      int references films (id),
    user_id      int references users (id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE if not exists user_friends
(
    id           int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user1_id     int references users (id),
    user2_id     int references users (id),
    initiator_id int references users (id),
    PRIMARY KEY (user1_id, user2_id)
);
